Feature/ticket 1/project setup
programacion-6/ExpenseTrackerGrupo5 pull request #1
Opened 2024-09-16 17:46 UTC by luiggy-mamani-jalafund

# US 1 - Project Initialization
[Go to US - Link](https://trello.com/c/NR1GSWnF/1-us-1-project-setup)

## What did I do?
- Api initializaction
- Code Style
- Global environment configuration

2024-09-16 18:00 UTC, SebasthianSalpozz requested changes

2024-09-16 18:00 UTC, SebasthianSalpozz commented on .gitignore
> +obj
You missed the endline of the file

2024-09-16 18:00 UTC, SebasthianSalpozz commented on global.json
> +}
You also missed the endline of the file :D

2024-09-16 18:03 UTC, luiggy-mamani-jalafund commented on .gitignore
> +obj
what do you mean? could u give me an example?

2024-09-16 20:52 UTC, samuel-escalera-jalafund commented on .gitignore
The .gitignore can be improved, adding other files generated automatic or generated for the IDEs, eg:
# Ignore files generated by Visual Studio
.vscode/
*.vs
*.vscode

# Ignore directories for build outputs
bin/
obj/

# Ignore Rider/IDEA project files
.idea/
*.sln.iml

# Ignore user-specific files
*.user
*.rsuser
*.suo

# Ignore Visual Studio working files
.vscode/settings.json
.vscode/tasks.json
.vscode/launch.json

# Ignore package manager output
packages/

2024-09-16 22:21 UTC, luiggy-mamani-jalafund commented on .gitignore
> +obj
Done, it isn't reflected in the GitHub changes tho

![Screenshot from 2024-09-16 18-18-11](https://github.com/user-attachments/assets/23866741-43ad-4266-9a6d-81032695236d)

2024-09-16 22:21 UTC, luiggy-mamani-jalafund commented on global.json
> +}
Done, it isn't reflected in the GitHub changes tho

![Screenshot from 2024-09-16 18-18-23](https://github.com/user-attachments/assets/743429b6-f78c-48ba-b97f-4eb0a262f7c5)

2024-09-16 22:21 UTC, luiggy-mamani-jalafund commented on .gitignore
Done

2024-09-17 00:16 UTC, samuel-escalera-jalafund approved these changes
God job

2024-09-17 15:51 UTC, SebasthianSalpozz approved these changes
good job

2024-09-17 18:43 UTC, merged